version: '2.2'

services:
  django:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=oiajaoa1i8auas9098
      - ALLOWED_HOSTS=localhost,127.0.0.1